### ISSUE TITLE
Acestream from command line

### ISSUE THREAD

**Issue by alesnav** [tarasian666/acestream#2]
Hello,

How do you start playing an Acestream channel from command line?

Thanks!

**Comment by tarasian666** [comment]
Hello,
I'm not doing this because it is simpler way. I have implemented webserver into this engine.
For example: to play Acestream channel with pid e87ba3d6fbe447cfee0f21488e03029b514fdc7d
you need open url in player (for example vlc) http://127.0.0.1:6878/LOAD/PID=e87ba3d6fbe447cfee0f21488e03029b514fdc7d
where 127.0.0.1 is ip of machine where acestream engine is started
if you have not pid but torrent file (.acelive) of channel http://127.0.0.1:6878/LOAD/TORRENT=http://url.to/channel.acestream
etc.

**Comment by alesnav** [comment]
Perfect!

I have published a new repository including your code. It's available [here](https://github.com/alesnav/p2ptv-pi).

It does support Sopcast & AceStream from CLI using OMXPlayer.

Thanks!
